# Generated by Django 5.2.7 on 2025-10-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='введите название фильма')),
                ('image', models.ImageField(upload_to='films/', verbose_name='загрузите фото')),
                ('description', models.TextField(verbose_name='Укажите описание фильма')),
                ('director', models.CharField(default='Иванов Иван', max_length=100, verbose_name='укажите режисера')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Мелодрамма', 'Мелодрамма'), ('Боевик', 'Боевик')], max_length=100, verbose_name='Укажите жанр')),
                ('country', models.CharField(default='США', max_length=100, verbose_name='укажите страну')),
                ('duration', models.PositiveIntegerField(default=3, verbose_name='укажите продолжительность фильма')),
                ('trailer', models.URLField(verbose_name='вставьте ссылку на трейлер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
