# Generated by Django 5.2.7 on 2025-10-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
