# Generated by Django 5.2.7 on 2025-11-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='KG', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.car')),
            ],
        ),
    ]
